UniversityWebsiteApplication/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from WebApp.views import home_view as hv


urlpatterns = [
    path('', hv, name='home-index'),
    path('blog/', include('blog.urls')),
    path('cv/', include('cv.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index_view, name='blog-index_view'),
    path('posts', views.index_view),
    path('posts/details/<uuid:pk>', views.blog_post_details, name='blog-post_details'),
    path('posts/manage', views.blog_manage_posts, name='blog-manage-posts'),
    path('posts/manage/delete/<uuid:pk>', views.blog_delete_post, name='blog-delete_post'),
    path('posts/manage/toggleactive/<uuid:pk>', views.blog_toggle_active, name='blog-toggle-active'),
    path('posts/new/', views.blog_new_view, name='blog-new-view'),
    path('posts/new/image-upload', views.blog_upload_image, name='blog-add-image'),
    path('posts/test', views.blog_test, name='blog-test'),
]

cv/urls.py
from django.urls import path
from .views import (index, manage, add_basic_information, add_past_education, add_skill, add_hobby, add_past_experience,
					add_subject_to_education, delete_education, toggle_subject, delete_subject, toggle_skill,
					delete_skill, toggle_hobby, delete_hobby, toggle_basic_information, delete_basic_information,
					add_past_experience_institute, delete_past_experience, delete_experience,
					update_experience_with_finish_date)


urlpatterns = [
	path("", index, name='cv-index'),
	path("manage", manage, name='cv-manage'),
	path("manage/add/BasicInformation", add_basic_information, name='cv-add-basic-information'),
	path("manage/toggle/BasicInformation/<int:pk>", toggle_basic_information, name="cv-toggle-BasicInformation"),
	path("manage/delete/BasicInformation/<int:pk>", delete_basic_information, name="cv-delete-BasicInformation"),
	path("manage/add/PastEducation", add_past_education, name='cv-add-past-education'),
	path("manage/add/PastEducation/<int:pk>", add_subject_to_education, name="cv-add-subject-to-education"),
	path("manage/delete/PastEducation/<int:pk>", delete_education, name="cv-delete-education"),
	path("manage/toggle/subject/<int:pk>", toggle_subject, name="cv-toggle-subject"),
	path("manage/delete/subject/<int:pk>", delete_subject, name="cv-delete-subject"),
	path("manage/add/skill", add_skill, name='cv-add-skill'),
	path("manage/toggle/skill/<int:pk>", toggle_skill, name="cv-toggle-skill"),
	path("manage/delete/skill/<int:pk>", delete_skill, name="cv-delete-skill"),
	path("manage/add/hobby", add_hobby, name='cv-add-hobby'),
	path("manage/toggle/hobby/<int:pk>", toggle_hobby, name="cv-toggle-hobby"),
	path("manage/delete/hobby/<int:pk>", delete_hobby, name="cv-delete-hobby"),
	path("manage/add/PastExperienceInstitute", add_past_experience_institute, name='cv-add-past-experience-institute'),
	path("manage/add/PastExperience/<int:pk>", add_past_experience, name='cv-add-experience'),
	path("manage/delete/PastExperience/<int:pk>", delete_past_experience, name='cv-delete-past-experience'),
	path("manage/delete/experience/<int:pk>", delete_experience, name='cv-delete-experience'),
	path("manage/update/experience/<int:pk>", update_experience_with_finish_date, name='cv-update-experience-with-finish-date')
]

blog/models.py
import os
import uuid

from django.db import models
from UniversityWebsiteApplication.settings import MEDIA_ROOT

# Create your models here.
from django.utils.deconstruct import deconstructible


class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=128)
    synopsis = models.CharField(max_length=256, blank=True)
    raw_body_location = models.CharField(max_length=128)
    html_fragment_location = models.CharField(max_length=128)
    date_finished = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)


class BlogPostImages(models.Model):
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    image_path = models.CharField(max_length=128)


class BlogImageToMove(models.Model):
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    temp_path = models.CharField(max_length=128)
    new_path = models.CharField(max_length=128)


class Tags(models.Model):
    tag = models.CharField(max_length=32)


@deconstructible
class UploadToPathAndRename(object):

    def __init__(self, path):
        self.sub_path = path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        # set filename as random string
        filename = '{}.{}'.format(uuid.uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(self.sub_path, filename)


class BlogImageUpload(models.Model):
    caption = models.CharField(max_length=256, blank=True)
    alt_text = models.CharField(max_length=256, blank=True)
    image = models.ImageField(upload_to=UploadToPathAndRename(os.path.join(MEDIA_ROOT, 'temp/')))

    def __str__(self):
        return ("Caption: " + self.caption + "\n"
                + "Alt_Text: " + self.alt_text + "\n"
                + "Image Path: " + self.image.path + "\n"
                + "Image Width:" + str(self.image.width) + "\n"
                + "Image Height:" + str(self.image.height) + "\n")


class BlogExceptions(models.Model):
    exc_type = models.CharField(max_length=512, blank=True)
    value = models.CharField(max_length=512, blank=True)
    traceback = models.CharField(max_length=512, blank=True)
    date_excepted = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Type: {self.exc_type}\nValue: {self.value}\nTraceback: {self.traceback}\nDate Occured: "\
              f"{self.date_excepted}"

blog/forms.py
from django import forms
from django.forms import ModelForm

from .models import BlogImageUpload


class CreatePost(forms.Form):
    blog_title = forms.CharField(label='Post Title:', max_length=150)
    body = forms.CharField(label='Body:', widget=forms.Textarea)

    def __str__(self):
        return "Title: " + self.cleaned_data['blog_title'] + "\n" + "Body: " + self.cleaned_data['body']


class UploadImage(ModelForm):
    class Meta:
        model = BlogImageUpload
        fields = ['caption', 'alt_text', 'image']

blog/views.py
import os
from uuid import uuid4

from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .forms import CreatePost, UploadImage
from .models import BlogImageUpload, Post, BlogImageToMove, BlogPostImages
from .Util import BlogBodyParser as bbp
from .Util.Exceptions import report_exception

from GenericUtils import media_utils


# Create your views here.
def index_view(request):
	posts = Post.objects.filter(active=True)
	return render(request, 'blog/index.html', {'title': 'Blog', 'posts': posts})


def blog_post_details(request, pk):
	post = get_object_or_404(Post, pk=pk)

	body = _get_blog_body(post)

	return render(request, "blog/post_details.html", {'post': post, 'post_body': body})


def _get_blog_body(post: Post):
	try:
		with open(post.html_fragment_location, "r") as fis:
			body = fis.read()
	except OSError:
		report_exception()
	else:
		return body


@login_required
def blog_new_view(request):
	if request.method == "POST":
		form = CreatePost(request.POST)

		if form.is_valid():
			data = request.POST.copy()
			blog_title = data.get('blog_title')
			blog_body = data.get('body')
			blog_synopsis = data.get('synopsis')

			# Create a blog instance, and save it to get an ID for the current blog
			post = Post(title=blog_title, synopsis=blog_synopsis, active=True)
			post.save()

			parsed_body = bbp.parse_body(blog_body, post)

			""" Move the images (if any) that were referenced in the body to their final static location """
			__move_images_to_media_root(post)

			""" Save the body to a HTML file so that it can be loaded when somebody goes to view it, as well as the raw
			 	text that makes up the body of the blog """
			files_created_successfully = _save_html_and_body_string_to_file(raw_body=blog_body, blog_post=post,
																			html_string=parsed_body)

			if files_created_successfully:
				post.save()

			return redirect('blog-index_view', permanent=True)
	else:
		form = CreatePost()
		image_upload_form = UploadImage()
		return render(request, 'blog/new_post.html',
					  {'title': 'New Post', 'form': form, 'imageUploadForm': image_upload_form})


def blog_test(request):
	return render(request, 'blog/test.html', {'title': 'Test'})


def create_image_tag(name):
	return r'\img{' + str(name) + '}'


@login_required
def blog_manage_posts(request):
	all_posts = Post.objects.all()
	return render(request, 'blog/manage_posts.html', {'title': "Manage posts", 'posts': all_posts})


@login_required
def blog_toggle_active(request, pk: uuid4):
	post = get_object_or_404(Post, pk=pk)
	post.active = not post.active
	post.save()
	return redirect('/blog/posts/manage')


@login_required
def blog_delete_post(request, pk: uuid4):
	post = get_object_or_404(Post, pk=pk)

	if request.method == "POST":
		html_fragment = post.html_fragment_location
		raw_body = post.raw_body_location

		media_utils.delete_file_in_media([html_fragment, raw_body])

		post.delete()

		return redirect('blog-manage-posts', permanent=True)

	return render(request, 'blog/delete_post.html', {'title': 'Delete Blog Post', 'post': post})


def __move_images_to_media_root(blog_post: Post):
	# Get a list of all the objects with the current post's ID
	images_to_move = BlogImageToMove.objects.filter(post_id=blog_post.id)

	for image in images_to_move:
		# Create a new tuple to pass to the move image method
		temp_path, new_path = image.temp_path, image.new_path

		# Call the method, capturing the return value of the method
		success = _move_image_to_media_root(temp_path, new_path)

		# If the method is successful in moving the image, then delete the entry in the database
		if success:
			# Keep a reference to this image, so that in the future if the blog post is deleted, the related images can
			# be removed at the same time
			blog_image = BlogPostImages(post_id=blog_post, image_path=image.new_path)
			blog_image.save()
			# Delete the image from the table as it's been moved now
			image.delete()


def _save_html_and_body_string_to_file(raw_body: str, blog_post: Post, html_string: str):
	# Firstly, get the required path to the correct location to store the HTML fragment
	html_fragment_path = media_utils.get_new_path_in_media_root(f"{str(blog_post.id)}.html")
	raw_body_path = media_utils.get_new_path_in_media_root(f"{str(blog_post.id)}.txt")

	if _write_file(html_fragment_path, str(html_string)) and _write_file(raw_body_path, raw_body):
		blog_post.html_fragment_location = html_fragment_path
		blog_post.raw_body_location = raw_body_path
		blog_post.save()
		return True
	else:
		return False


def _write_file(path_to_write: str, data_to_write: str):
	# If the path does not exist, then create it
	if not os.path.exists(path_to_write):
		to_create = "/".join(path_to_write.split("/")[:-1])
		__create_directory_structure(to_create)

	# Save the files to disk
	try:
		with open(path_to_write, "w") as fos:
			fos.write(data_to_write)
	except OSError:
		report_exception()
		return False
	else:
		return True


def __create_directory_structure(path_to_create: str):
	try:
		if not os.path.exists(path_to_create):
			os.makedirs(path_to_create)
	except OSError:
		report_exception()
		return False
	else:
		return True


def _move_image_to_media_root(old_path: str, new_path: str):
	# Get the directory structure to create ready to try and create it
	new_image_directory = "/".join(new_path.split("/")[:-1])

	# If the directory can be created (or already exists), then move the file to the new location
	if __create_directory_structure(new_image_directory):
		os.rename(old_path, new_path)
		return True
	else:
		return False


@login_required
def blog_upload_image(request):
	# Check request is AJAX call, and that method is POST
	if request.is_ajax() and request.method == 'POST':
		form = UploadImage(request.POST, request.FILES)

		if form.is_valid():
			# Create a new BlogImageUpload object
			new_image = BlogImageUpload()

			# Set data in new object reference
			new_image.caption = form.cleaned_data['caption']
			new_image.image = form.cleaned_data['image']
			new_image.alt_text = form.cleaned_data['alt_text']

			# Save the new instance
			new_image.save()

			# Retrieve the new instance from the database (to return name to form so that the image can be linked to
			# this post)
			last_obj = BlogImageUpload.objects.latest('id')

			# Format the return image name into the correct tag format so that this code isn't in the JS included with
			# the website
			file_name = str(last_obj.image.file).split('/')[-1]
			image_tag = create_image_tag(file_name)

			return JsonResponse({'result': 'success', 'image_tag': image_tag})
		else:
			return JsonResponse({'result': 'error', 'message': 'File failed to upload!'})

blog/templates/blog/blog_base.html
{% extends "UniversityWebsiteApplication/base.html" %}
{% load static %}

{% block stylesheet %}<link rel="stylesheet" type="text/css" href="{% static 'css/blog_style.css' %}"/>{% endblock stylesheet %}

blog/templates/blog/delete_post.html
{% extends 'blog/blog_base.html' %}

{% block body %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <h1>Are you sure you want to do this?</h1>
        <br/>
        <h2>This action cannot be undone</h2>
        <hr/>
        <h3>Post Deleting:</h3>
        <form method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <th><label for="post_id">id</label></th>
                    <td><input id="post_id" value="{{ post.id }}" disabled/></td>
                </tr>
                <tr>
                    <th><label for="post_title">Title</label></th>
                    <td><input id="post_title" value="{{ post.title }}" disabled/></td>
                </tr>
                <tr>
                    <th><label for="post_synopsis">Synopsis</label></th>
                    <td><input id="post_synopsis" value="{{ post.synopsis }}" disabled/></td>
                </tr>
                <tr>
                    <th><label for="post_raw_body">Raw Body Location</label></th>
                    <td><input id="post_raw_body" value="{{ post.raw_body_location }}" disabled/></td>
                </tr>
                <tr>
                    <th><label for="post_html_fragment">Post HTML Fragment</label></th>
                    <td><input id="post_html_fragment" value="{{ post.html_fragment_location }}" disabled/></td>
                </tr>
                <tr>
                    <th><label for="post_date_finished">Date Finished</label></th>
                    <td><input id="post_date_finished" value="{{ post.date_finished|date:"d/m/Y" }}" disabled/></td>
                </tr>
                <tr>
                    <th><label for="post_active">Post Active</label></th>
                    <td><input id="post_active" value="{{ post.active }}" disabled/></td>
                </tr>
            </table>
            <button class="btn btn-outline-danger" type="submit">Delete Post</button>
        </form>
        <hr/>
        <a href="{% url 'blog-manage-posts' %}" class="text-info text-center">Back To List</a>
    </div>
    <div class="col-3"></div>
</div>
{% endblock body %}

blog/templates/blog/index.html
{% extends 'blog/blog_base.html' %}

{% block body %}
    <div class="row">
        <div class="col">
            <h1 class="text-center">Blog Posts</h1>
        </div>
    </div>
    <hr/>
<div class="row">
    <div class="col-2"></div>
    <div id="blog_main_section" class="col-7">
        {% if posts|length == 0 %}
            <h3 class="text-center">No posts to show, sorry!</h3>
        {% else %}
        {% for post in posts %}
            <div class="blog_card">
                <h2><a href="{% url 'blog-post_details' pk=post.pk %}">{{ post.title }}</a></h2>
                <hr/>
                <h6>{% if post.synopsis|length != 0 %}{{ post.synopsis }}{% else %}No synopsis given{% endif %}</h6>
                <br>
                <a href="{% url 'blog-post_details' pk=post.pk %}" class="text-info">Read More</a>
            </div>
        {% endfor %}
    {% endif %}
    </div>
<div class="col-3">
    {% if user.is_authenticated %}
        <div id="blog_sidebar">
            <h3>Blog Post Actions</h3>
            <hr/>
            <a href="posts/new"><button class="btn btn-outline-success">Add New Blog Post</button></a>
            <hr/>
            <a href="posts/manage"><button class="btn btn-outline-warning">Manage Posts</button></a>
            <hr/>
        </div>
    {% endif %}
</div>
</div>
{% endblock body %}

blog/templates/blog/manage_posts.html
{% extends "blog/blog_base.html" %}

{% block body %}
    <div class="row">
    <div class="col-1"></div>
    <div class="col" id="blog_manage_div">
        <table>
            <tr id="blog_manage_table">
                <th class="table_header" id="blog_table_title">Title</th>
                <th class="table_header" id="blog_table_synopsis">Synopsis</th>
                <th class="table_header" id="blog_table_raw_body">Raw Body Location</th>
                <th class="table_header" id="blog_table_html_fragment">HTML Fragment Location</th>
                <th class="table_header text-center" id="blog_table_date_finished">Date Finished</th>
                <th class="table_header text-center" id="blog_table_active">Active</th>
                <th class="table_header text-center" id="blog_table_actions">Actions</th>
            </tr>
            {% if posts|length == 0 %}
            <tr>
                <td colspan="7" class="text-center" id="blog_manage_no_posts"><h2>No blog posts to manage!</h2></td>
            </tr>
            {% else %}
            {% for post in posts %}
                <tr id="blog_manage_table">
                    <td>{{ post.title }}</td>
                    <td>{{ post.synopsis }}</td>
                    <td>{{ post.raw_body_location }}</td>
                    <td>{{ post.html_fragment_location }}</td>
                    <td class="text-center">{{ post.date_finished|date:"d/m/Y" }}</td>
                    <td class="text-center">{% if post.active %}Yes{% else %}No{% endif %}</td>
                    <td class="text-center"><a href="{% url 'blog-post_details' pk=post.pk %}" class="text-info">View</a>|<a href="{% url 'blog-toggle-active' pk=post.pk %}" class="text-info">Toggle Active</a>|<a href="{% url 'blog-delete_post' pk=post.pk %}" class="text-danger">Delete</a></td>
                </tr>
            {% endfor %}
            {% endif %}
        </table>
    </div>
    <div class="col-1"></div>
    </div>
{% endblock body %}

blog/templates/blog/new_post.html
{% extends 'blog/blog_base.html' %}

{% block body %}
    <div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="body-content col-8">
            <div class="text-center">
                <h2>New Post</h2>
                <hr/>
                <button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#image_upload_modal">Upload Image</button>
                <hr/>
                <form id="add_post_form" method="post" class="post-form">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th><label for="id_blog_title">Blog Title:</label></th>
                            <td><input type="text" name="blog_title" maxlength="150" required id="id_blog_title" autocomplete="off"/></td>
                        </tr>
                        <tr>
                            <th><label for="id_synopsis">Synopsis:</label></th>
                            <td><textarea name="synopsis" rows="3" maxlength="256" required id="id_synopsis" autocomplete="off"></textarea></td>
                        </tr>
                        <tr>
                            <th id="blog_body"><label for="id_body">Body:</label></th>
                            <td><textarea name="body" rows="25" required id="id_body" autocomplete="off"></textarea></td>
                        </tr>
                    </table>
                    <hr />
                    <div class="formButtons">
                        <button type="submit" class="blog-btn btn btn-outline-success">Save Post</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col"></div>
    </div>
    </div>

    <div class="modal" id="image_upload_modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3>Add Image To Blog</h3>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form enctype="multipart/form-data" id="image_upload_form" method="POST">
                            <table>
                                {{ imageUploadForm.as_table }}
                            </table>
                            <button type="submit">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

{% block scripts %}
        <script type="application/javascript">
        let post_body = $('#id_body');
        let image_upload_modal = $("#image_upload_modal")

        function emptyInput(input) {
            input.val("");
        }

        function insertTag(val) {
            const cursorPos = post_body.prop('selectionStart');
            const v = post_body.val();
            const textBefore = v.substring(0, cursorPos);
            const textAfter = v.substring(cursorPos, v.length);

            post_body.val(textBefore + val + textAfter);
            setCaretToPos(post_body, cursorPos + val.length)
        }

        function setSelectionRange(input, selectionStart, selectionEnd) {
            if (input.setSelectionRange) {
            input.focus();
            input.setSelectionRange(selectionStart, selectionEnd);
            }
            else if (input.createTextRange) {
            var range = input.createTextRange();
            range.collapse(true);
            range.moveEnd('character', selectionEnd);
            range.moveStart('character', selectionStart);
            range.select();
            }
        }

        function clearUploadModal() {
            $('#id_caption').val("");
            $('#id_alt_text').val("");
            image_upload_modal.modal('hide');
        }

        function setCaretToPos (input, pos) {
          setSelectionRange(input, pos, pos);
        }

        $(document).ready(function() {
            $('#id_blog_title').trigger("input");


            $("#image_upload_form").submit(function(e) {
                e.preventDefault();

                let caption = $('#id_caption').val();
                let alt_text = $('#id_alt_text').val();
                let image =  $('#id_image').prop('files')[0];

                if(image === undefined)
                    return;

                let formData = new FormData();
                formData.append('caption', caption);
                formData.append('image', image);
                formData.append('alt_text', alt_text);

                const csrftoken = $('[name=csrfmiddlewaretoken]').val();

                function csrfSafeMethod(method) {
                    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                }

                $.ajaxSetup({
                    beforeSend: function (xhr, settings) {
                        if(!csrfSafeMethod(settings.type) && !this.crossDomain) {
                            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                        }
                    }
                });

                $.ajax({
                    url: "{% url 'blog-add-image' %}",
                    type: 'POST',
                    data: formData,
                    success: function(response) {
                        if(response.error) {
                            $.each(response.errors, function(name, error) { console.log(name, error) })
                        } else {
                            let image_tag = response['image_tag'];
                            if(image_tag !== null) {
                                insertTag(image_tag);
                            }

                            clearUploadModal();
                        }
                    },
                    cache: false,
                    contentType: false,
                    processData: false
                });
            });
        });
    </script>
{% endblock scripts %}

blog/templates/blog/post_details.html
{% extends "blog/blog_base.html" %}

{% block body %}
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <h1>{{ post.title }}</h1>
            <br/>
            <span class="text-muted">{{ post.date_finished|date:"d M, Y" }}</span>
            <hr/>
            {% autoescape off %}
            {{ post_body }}
            {% endautoescape %}
        </div>
        <div class="col-2"></div>
    </div>
{% endblock %}

blog/templates/blog/test.html
{% extends 'UniversityWebsiteApplication/base.html' %}

{% block body %}
{{ form.as_table }}
{% endblock body %}